Repository AY2324S1-CS2103T-W15-4/tp, pull requests merged in 2023-11, with the labels that each got.

#151 Edit parser to ignore letter case for commands
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
Labels: type.Bug

#154 Fix bugs
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddCourseCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearCourseCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCourseCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditCourseCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/commands/PendingQuestionCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/commands/ResetCourseCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/course/CourseName.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/SortCriteria.java
  src/main/java/seedu/address/ui/CourseCard.java
  src/main/resources/view/DarkTheme.css
Labels: type.Bug

#158 Add Command History
  docs/UserGuide.md
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium

#160 Make UI changes
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CourseCard.java
  src/main/java/seedu/address/ui/CourseListPanel.java
  src/main/java/seedu/address/ui/ExternalLinks.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CombinedPanel.fxml
  src/main/resources/view/CourseListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Low

#162 Fix UI double variable bug
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug

#161 Fix bugs
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PendingQuestionCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/PendingQuestionCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
Labels: type.Bug

#168 Make UI changes for lists
  src/main/java/seedu/address/ui/CourseCard.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/images/icons/email.png
  src/main/resources/images/icons/notes.png
  src/main/resources/images/icons/person.png
  src/main/resources/images/icons/question.png
  src/main/resources/view/CourseListCard.fxml
  src/main/resources/view/StudentListCard.fxml
Labels: priority.Medium

#170 Fix bug in EditCommand
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug

#164 Implement list pq command
  src/main/java/seedu/address/logic/commands/ListPendingQuestionsCommand.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
  src/main/java/seedu/address/logic/parser/ListPendingQuestionsCommandParser.java
Labels: type.Enhancement

#173 Fix ListPendingQuestionsCommand import
  src/main/java/seedu/address/logic/parser/ListPendingQuestionsCommandParser.java
Labels: type.Bug

#174 Fix reset bug
  src/main/java/seedu/address/logic/commands/HomeCommand.java
Labels: type.Bug

#175 Update validation for student name
  src/main/java/seedu/address/model/person/Name.java
Labels: type.Bug

#178 Edit formatting of success messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Enhancement, type.Bug

#181 Fix error messages for listing pending questions
  src/main/java/seedu/address/logic/commands/ListPendingQuestionsCommand.java
  src/main/java/seedu/address/logic/parser/ListPendingQuestionsCommandParser.java
Labels: type.Bug

#182 Edit input format of list pq
  src/main/java/seedu/address/logic/parser/ListPendingQuestionsCommandParser.java
Labels: type.Enhancement

#184 Add Input History and related files
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
  src/main/java/seedu/address/logic/parser/StageManager.java
  src/main/java/seedu/address/logic/parser/Stages.java
  src/main/java/seedu/address/storage/InputHistory.java
  src/main/java/seedu/address/storage/InputStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/DisplayPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task, type.Enhancement

#185 Fix name validation to allow whitespace
  src/main/java/seedu/address/model/person/Name.java
Labels: type.Bug

#186 Make UI changes for input history
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/storage/InputHistory.java
  src/main/java/seedu/address/storage/InputStorage.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug

#188 Make app UI changes
  src/main/resources/view/CourseListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StudentListCard.fxml
Labels: priority.Low

#190 Fix error message
  src/main/java/seedu/address/logic/commands/AddCourseCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, severity.VeryLow

#193 Update UG
  docs/UserGuide.md
  docs/images/.tiongjjyi.png.icloud
Labels: documentation, priority.High

#240 Edit sort comparators to use email as tiebreaker
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/person/UniqueStudentList.java
Labels: type.FunctionalityBug

#241 Test and documentation
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/testutil/SortCriteriaBuilder.java
Labels: type.Task

#246 Add test cases and fix findCommand bug
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicates/AllPendingQuestionPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PqContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/ListPendingQuestionsCommandTest.java
  src/test/java/seedu/address/logic/commands/PendingQuestionCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/parser/ListPendingQuestionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PendingQuestionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalCourses.java
Labels: type.Task, type.FunctionalityBug

#247 Fix Find Bug
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PqContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/RemarkContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/TagFilterPredicate.java
Labels: type.FunctionalityBug

#250 Fix double prefix bug for Remark & PQ
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/PendingQuestionCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
Labels: type.FunctionalityBug

#251 Fix UI for wrong command at wrong stage
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
Labels: type.FunctionalityBug

#252 Add ResetCourse when Select Course
  src/main/java/seedu/address/logic/commands/SelectCommand.java
Labels: type.FunctionalityBug

#253 Add tests for SortCommandParser
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/person/Field.java
  src/main/java/seedu/address/model/person/SortCriteria.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/testutil/SortCriteriaBuilder.java
Labels: type.Task

#256 Add tests for ResetCommand, ResetCourseCommand, ClearCommand
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/commands/ResetCourseCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetCourseCommandTest.java
  src/test/java/seedu/address/logic/parser/ResetCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ResetCourseCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalCourses.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task

#258 Fix UG links
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: PED.MustFix

#260 Add test cases
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCourseCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
Labels: type.Task

#261 Add tests for EditCommandParser and EditCourseCommandParser
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCourseCommandParserTest.java
Labels: type.Task

#262 Edit ParserUtilTest and add new tests
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Task

#276 Update PPP
  docs/team/sunzihan23.md
Labels: type.Task

#277 Update README.md
  README.md
  docs/images/course_display.png
Labels: documentation

#293 Edit UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#307 Create new package for Stage Manager
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/commands/ListPendingQuestionsCommand.java
  src/main/java/seedu/address/logic/commands/PendingQuestionCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
  src/main/java/seedu/address/logic/stagemanager/StageManager.java
  src/main/java/seedu/address/logic/stagemanager/Stages.java
  src/main/java/seedu/address/ui/CourseListPanel.java
  src/main/java/seedu/address/ui/DisplayPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCourseCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCourseCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HomeCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPendingQuestionsCommandTest.java
  src/test/java/seedu/address/logic/commands/PendingQuestionCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/CodeSphereParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/address/logic/stagemanager/StageManagerTest.java
Labels: severity.VeryLow

#311 Fix UG Links
  docs/UserGuide.md
Labels: documentation

#313 Add DevanshuBisht's PPP
  docs/images/about_us/devanshubisht.png
  docs/team/devanshubisht.md
Labels: documentation

#317 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/about_us/.tiongjjyi.png.icloud
  docs/team/phiphi-tan.md
  docs/team/tiongjjyi.md
Labels: type.Task

#323 Update DG for UI and Storage
  docs/DeveloperGuide.md
  docs/diagrams/UiActivityDiagram.puml
  docs/images/UiActivityDiagram.png
Labels: documentation

#325 Add SampleData
  src/main/java/seedu/codesphere/model/CourseList.java
  src/main/java/seedu/codesphere/model/util/SampleDataUtil.java
Labels: type.Task

#332 Add manual testing instructions in DG appendix
  docs/DeveloperGuide.md
Labels: type.Task

#331 Branch add success screenshots
  docs/UserGuide.md
  docs/images/CommandSuccessScreenshots/AddCourseSuccess.png
  docs/images/CommandSuccessScreenshots/AddStudentSuccess.png
  docs/images/CommandSuccessScreenshots/ClearCourseSuccess.png
  docs/images/CommandSuccessScreenshots/ClearStudentListSuccess.png
  docs/images/CommandSuccessScreenshots/DeleteCourseSuccess.png
  docs/images/CommandSuccessScreenshots/DeleteStudentSuccess.png
  docs/images/CommandSuccessScreenshots/EditCourseSuccess.png
  docs/images/CommandSuccessScreenshots/EditStudentSuccess.png
  docs/images/CommandSuccessScreenshots/FindCourseSuccess.png
  docs/images/CommandSuccessScreenshots/FindStudentSuccess.png
  docs/images/CommandSuccessScreenshots/HelpScreen.png
  docs/images/CommandSuccessScreenshots/HomeSuccess.png
  docs/images/CommandSuccessScreenshots/ListPQSuccess.png
  docs/images/CommandSuccessScreenshots/PQSuccess.png
  docs/images/CommandSuccessScreenshots/RemarkSuccess.png
  docs/images/CommandSuccessScreenshots/RemoveSuccess.png
  docs/images/CommandSuccessScreenshots/ResetStudentSuccess.png
  docs/images/CommandSuccessScreenshots/ResetSuccess.png
  docs/images/CommandSuccessScreenshots/SelectSuccess.png
  docs/images/CommandSuccessScreenshots/SortSuccess.png
Labels: documentation

#336 Create author tags
  docs/DeveloperGuide.md
  src/main/java/seedu/codesphere/logic/commands/RemarkCommand.java
  src/main/java/seedu/codesphere/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/codesphere/model/student/Remark.java
  src/main/java/seedu/codesphere/ui/CombinedPanel.java
  src/main/java/seedu/codesphere/ui/CommandBox.java
  src/main/java/seedu/codesphere/ui/CourseCard.java
  src/main/java/seedu/codesphere/ui/CourseListPanel.java
  src/main/java/seedu/codesphere/ui/DisplayPanel.java
  src/main/java/seedu/codesphere/ui/ExternalLinks.java
  src/main/java/seedu/codesphere/ui/HelpWindow.java
  src/main/java/seedu/codesphere/ui/SplashPanel.java
  src/main/java/seedu/codesphere/ui/StudentCard.java
  src/main/java/seedu/codesphere/ui/StudentListPanel.java
Labels: documentation

#340 Update PPP
  docs/team/sunzihan23.md
Labels: documentation

#346 Fix website UI bugs
  .github/workflows/gradle.yml
  docs/AboutUs.md
  docs/images/Ui.png
  docs/index.md
Labels: documentation

#349 Update sort command implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandClassDiagram.puml
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/SortCommandSequenceDiagram.png
Labels: documentation

#350 Add activity diagram for sort command in UG
  docs/DeveloperGuide.md
  docs/diagrams/SortCommandActivityDiagram.puml
  docs/images/SortCommandActivityDiagram.png
Labels: documentation

#351 Update DG section in PPP
  docs/team/sunzihan23.md
Labels: documentation

#352 Fix error in sort command
  docs/DeveloperGuide.md
Labels: documentation

#361 Update FindCommand in DG and Add credits for StageManager
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/images/FindCommandActivityDiagram.png
  docs/images/FindCommandClassDiagram.png
  docs/images/FindCommandSequenceDiagram.png
  src/main/java/seedu/codesphere/logic/stagemanager/StageManager.java
Labels: documentation

#369 Edit PPP
  docs/team/devanshubisht.md
  src/main/java/seedu/codesphere/logic/commands/AddCourseCommand.java
Labels: documentation

#368 Add line breaks for UG
  docs/UserGuide.md
Labels: documentation

#364 Make documentation changes
  docs/DeveloperGuide.md
  src/main/java/seedu/codesphere/logic/commands/RemarkCommand.java
  src/main/java/seedu/codesphere/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/codesphere/model/student/Remark.java
  src/main/java/seedu/codesphere/ui/DisplayPanel.java
Labels: documentation

#370 Update PPP and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/devanshubisht.md
Labels: documentation

#371 Update PPP
  docs/team/devanshubisht.md
Labels: documentation

#372 Update PPP to keep within 2 pages
  docs/team/devanshubisht.md
Labels: documentation

#373 Update PPP to fit within 2 pages
  docs/team/devanshubisht.md
Labels: documentation

#381 Update UG
  docs/UserGuide.md
Labels: documentation

#383 Fix checkstyle
  docs/DeveloperGuide.md
Labels: documentation

#384 Update PPP
  docs/team/sunzihan23.md
Labels: documentation

#385 Update Phi PPP
  docs/team/phiphi-tan.md
Labels: documentation

#386 Edit formatting of PPP
  docs/team/sunzihan23.md
Labels: documentation

#387 Fix formatting for UG
  docs/UserGuide.md
Labels: documentation

#389 Fix RepoSense link for PPP
  docs/team/sunzihan23.md
Labels: documentation

#391 Update DG for InputHistory
  docs/DeveloperGuide.md
  docs/diagrams/RetrieveInputHistoryActivityDiagram.puml
  docs/diagrams/StoreInputHistoryActivityDiagram.puml
  docs/images/RetrieveInputHistoryActivityDiagram.png
  docs/images/StoreInputHistoryActivityDiagram.png
Labels: documentation

#395 Update PPP
  docs/team/phiphi-tan.md
Labels: documentation
