Repository AY2324S1-CS2103T-W15-4/tp, pull requests merged in 2023-10, with the labels that each got.

#64 Update README.md
  README.md
Labels: documentation

#71 Change from MarkBind to Jerkyl
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_data/projects.yml
  docs/_includes/custom-head.html
  docs/_includes/head.html
  docs/_includes/header.html
  docs/_layouts/alt-page.html
  docs/_layouts/default.html
  docs/_layouts/page.html
  docs/_markbind/layouts/default.md
  docs/_markbind/variables.json
  docs/_markbind/variables.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-mixins.scss
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/custom-variables.scss
  docs/_sass/minima/initialize.scss
  docs/_sass/minima/skins/classic.scss
  docs/_sass/minima/skins/solarized-dark.scss
  docs/_sass/minima/skins/solarized.scss
  docs/assets/css/style.scss
  docs/index.md
  docs/package-lock.json
  docs/package.json
  docs/site.json
Labels: documentation

#74 update config.yml
  docs/_config.yml
Labels: documentation

#83 Update EditCourseCommand.java
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/address/logic/commands/EditCourseCommand.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
Labels: priority.High, type.Enhancement

#96 Change UI for Student stage
  src/main/java/seedu/address/ui/CombinedPanel.java
  src/main/java/seedu/address/ui/CourseListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CombinedPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#109 Minor edits to addCourseCommand and addCommand
  docs/images/.tiongjjyi.png.icloud
  docs/images/tiongjjyi.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddCourseCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCourseCommandParser.java
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/UniqueStudentList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateStudentException.java
  src/test/java/seedu/address/logic/parser/PendingQuestionCommandParserTest.java
Labels: type.Enhancement, type.Bug

#110 Update DG and Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/.tiongjjyi.png.icloud
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ComponentManagers.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
Labels: documentation, priority.High, type.Task

#113 Implement Remove Command to remove remark/ pending question
  docs/images/tiongjjyi.png
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/model/person/Student.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
Labels: type.Story, priority.Medium

#117 Add a use case and user story to DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#123 Update UserGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: documentation, priority.High

#115 Enable finding all existing questions
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/AllPendingQuestionPredicate.java
Labels: type.Story, priority.Low

#119 Add HomeCommand and HomeCommandParser
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
  src/main/java/seedu/address/logic/parser/HomeCommandParser.java
  src/main/java/seedu/address/logic/parser/StageManager.java
  src/test/java/seedu/address/logic/commands/HomeCommandTest.java
  src/test/java/seedu/address/logic/parser/HomeCommandParserTest.java
Labels: priority.High

#120 Add DisplayPanel to UI
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/ui/DisplayPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CombinedPanel.fxml
  src/main/resources/view/DisplayPanel.fxml
  src/main/resources/view/SplashPanel.fxml
Labels: type.Enhancement

#124 Update Adding PQ implementation in DG
  docs/DeveloperGuide.md
Labels: documentation

#125 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Medium

#127 Update DevGuide and UserGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#132 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Medium

#134 Edit SortCommand
  docs/images/.tiongjjyi.png.icloud
  docs/images/tiongjjyi.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCourseCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/course/SortCriteria.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Story, type.Enhancement

#136 Make UI changes
  src/main/java/seedu/address/logic/parser/StageManager.java
  src/main/java/seedu/address/ui/CourseCard.java
  src/main/java/seedu/address/ui/CourseListPanel.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/CourseListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StudentListPanel.fxml
Labels: type.Enhancement

#135 Add pending question count to course list
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/person/UniqueStudentList.java
  src/main/java/seedu/address/ui/CourseCard.java
  src/main/resources/view/CourseListCard.fxml
Labels: type.Enhancement

#138 Rename list command to reset command
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
  src/main/java/seedu/address/logic/parser/StageManager.java
  src/main/java/seedu/address/ui/CourseCard.java
  src/main/java/seedu/address/ui/CourseListPanel.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
  src/test/java/seedu/address/logic/parser/CourseListParserTest.java
Labels: type.Enhancement

#139 Add parser for ResetCommand
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
  src/main/java/seedu/address/logic/parser/ResetCommandParser.java
Labels: type.Bug

#141 Add ClearCourseCommand and edit ClearCommand
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearCourseCommand.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/person/UniqueStudentList.java
Labels: type.Enhancement, type.Bug

#140 Make UI changes for help
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/calendar.png
  src/main/resources/images/clock.png
  src/main/resources/images/codeSphere.png
  src/main/resources/images/codeSphere_logo.png
  src/main/resources/images/help_icon.png
  src/main/resources/images/info_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low

#146 Add find course feature and reset the course list after find
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCourseCommand.java
  src/main/java/seedu/address/logic/commands/ResetCourseCommand.java
  src/main/java/seedu/address/logic/parser/CodeSphereParser.java
  src/main/java/seedu/address/logic/parser/FindCourseCommandParser.java
  src/main/java/seedu/address/logic/parser/ResetCourseCommandParser.java
  src/main/java/seedu/address/model/course/CourseNameContainsKeywordsPredicate.java
Labels: type.Story, priority.Medium

#147 Fix code for delete after sort
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Bug

#150 Branch UI fix
  src/main/resources/images/codeSphere.png
  src/main/resources/images/codeSphere_full.png
  src/main/resources/view/CombinedPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SplashPanel.fxml
Labels: type.Bug
